### ISSUE TITLE
Webhook for new/updated Shopify products does not create new pages

### ISSUE THREAD

**Issue by melaniepatrick** [commonknowledge/leftbookclub#248] opened 2022-06-01 08:17 UTC
I just uploaded the new book for June on Shopify but it's not feeding through to the website. We had this problem previously so I just wanted to check whether there's a fix we can do? It's called The Jakarta Method. It looks fine on Shopify but it's not appearing on the books page.
I'd like to get it uploaded soon because now we feature a book during checkout (telling people which book they will receive) it's important I upload it at the right time. Thanks!

**Comment by janbaykara** [comment] 2022-06-01 10:08
Seen. I will run a manual sync now and then check why this is not automatically happening.

**Comment by janbaykara** [comment] 2022-06-01 10:12
The new book has been synced: https://leftbookclub.com/confirm-shipping/6/prod_LcPK2ze6AGTAgl/?

**Comment by melaniepatrick** [comment] 2022-06-01 10:15
thanks!

**Comment by janbaykara** [comment] 2022-09-14 10:21
Duplicate of #301

**Closed by janbaykara** 2022-09-14 10:21 UTC
